services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
     volumes:
      - ./data:/opt/keycloak/data/
      - ./providers:/opt/keycloak/providers/
    command: ["start-dev"]
    restart: unless-stopped
